import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Asset & Cashflow Manager",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <header>
        <nav>
          <ul>
            <li>Asset Overview</li>
            <li>Regular Cashflow</li>
            <li>Deposits</li>
            <li>Policy for Asset</li>
          </ul>
        </nav>
      </header>
      <body className={inter.className}>
        {children}
      </body>
      <footer></footer>
    </html>
  );
}
