import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import NavBar from "components/server/navigation";
import { SimpleLoginStatus } from "components/server/account/status";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Asset & Cashflow Manager",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="flex justify-between items-center p-4 bg-white dark:bg-gray-800 shadow-md">
          <Image
            src="/vercel.svg"
            alt="Vercel Logo"
            className="dark:invert"
            width={100}
            height={24}
            priority
            style={{ width: 100, height: 24 }}
          />
          <NavBar />
          <SimpleLoginStatus />
        </header>
        {children}
        <footer className="text-center p-4 bg-gray-200 dark:bg-gray-800"></footer>
      </body>
    </html>
  );
}